config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'recipes#index'

  resources :tags do
    member do
      post :add
      post :remove
    end
  end
  resources :ingredients
  resources :recipes do
    member do
      post :add
      post :remove
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :tags

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  # def index
  #   # Code for listing all albums goes here.
  #   @ingredients= Ingredient.all
  #   @ingredients= Ingredient.all
  #   @tags= Tag.all
  #   :index
  # end

  def new
    # Code for new album form goes here.
    @ingredient = Ingredient.new
    :new
  end

  def create
    # Code for creating a new album goes here.
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to root_path
    else
      render :new

  end

  def edit
    # Code for edit album form goes here.
    @ingredient = Ingredient.find(params[:id])
    render :edit
  end

  def show
    # Code for showing a single album goes here.
    @ingredient = Ingredient.find(params[:id])

    render :show
  end

  def update
    # Code for updating an album goes here.

    @ingredient= Ingredient.find(params[:id])
      if @ingredient.update(ingredient_params)
        redirect_to ingredient_path
      else
        render :edit
      end
  end

  def destroy
    # Code for deleting an album goes here.
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to root_path
  end
end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    # Code for listing all albums goes here.
    @recipes= Recipe.all
    @ingredients= Ingredient.all
    @tags= Tag.all

    :index
  end

  def new
    # Code for new album form goes here.
    @recipe = Recipe.new
    :new
  end

  def create
    # Code for creating a new album goes here.
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new

  end

  def edit
    # Code for edit album form goes here.
    @recipe = Recipe.find(params[:id])
    render :edit
  end

  def show
    # Code for showing a single album goes here.

  @recipe = Recipe.find(params[:id])

    @ingredients = []
    @tags = []
    Ingredient.all.each do |ingredient|
      if @recipe.ingredients.exclude?(ingredient)
        @ingredients.push(ingredient.name)

      end
    end

    Tag.all.each do |tag|
      if @recipe.tags.exclude?(tag)
        @tags.push(tag.name)

      end
    end

  render :show
  end

  def update
    # Code for updating an album goes here.

    @recipe= Recipe.find(params[:id])
      if @recipe.update(recipe_params)
        redirect_to recipe_path
      else
        render :edit
      end
  end

  def destroy
    # Code for deleting an album goes here.
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_path
  end

  def add
    @recipe = Recipe.find(params[:id])

    if params[:ingredient]

    ingredient = Ingredient.where(name: params[:ingredient].fetch("ingredient")).first

    @recipe.ingredients << ingredient



  elsif params[:tag]

    tag = Tag.where(name: params[:tag].fetch("tag")).first

    @recipe.tags << tag



  end

    redirect_to recipe_path


  end
end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :rating, :description)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # def index
  #   # Code for listing all albums goes here.
  #   @tags= Tag.all
  #   @tags= Tag.all
  #   @tags= Tag.all
  #   :index
  # end

  def new
    # Code for new album form goes here.
    @tag = Tag.new
    :new
  end

  def create
    # Code for creating a new album goes here.
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to root_path
    else
      render :new

  end

  def edit
    # Code for edit album form goes here.
    @tag = Tag.find(params[:id])
    render :edit
  end

  def show
    # Code for showing a single album goes here.
    @tag = Tag.find(params[:id])

    render :show
  end

  def update
    # Code for updating an album goes here.

    @tag= Tag.find(params[:id])
      if @tag.update(tag_params)
        redirect_to tag_path
      else
        render :edit
      end
  end

  def destroy
    # Code for deleting an album goes here.
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to root_path
  end


end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>




<h2>Recipes with this ingredient</h2>
<% if @ingredient.recipes.any? %>
<%  @ingredient.recipes.each do |recipe| %>

   <p><%=  link_to recipe.name, recipe_path(recipe.id) %></p>


<%  end %>
<%  else %>
<p>There are no Tags for this ingredient yet</p>

<%  end %>

<p><%= link_to "Edit", edit_ingredient_path(@ingredient) %></p>
<p><%= link_to "Delete", ingredient_path(@ingredient),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to ingredients", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBoxApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit  %>
<% end %>


<p><%= link_to "Add Ingredients to this Recipe", edit_recipe_path(@recipe) %></p>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% if @recipes.any? %>
<ul>
  <% @recipes.each do |recipe| %>
  <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no recipes yet.</p>
<% end %>


<p><%= link_to "Create new recipe", new_recipe_path %></p>


<h1>Tags</h1>

<% if @tags.any? %>
<ul>
  <% @tags.each do |tag| %>
  <li><%= link_to tag.name, tag_path(tag) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no tags yet.</p>
<% end %>


<p><%= link_to "Create new Tag", new_tag_path %></p>


<h1>Ingredients</h1>

<% if @ingredients.any? %>
<ul>
  <% @ingredients.each do |ingredient| %>
  <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no ingredients yet.</p>
<% end %>


<p><%= link_to "Create new Ingredient", new_ingredient_path %></p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit  %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<p><%= @recipe.description %></p>


<h2>Ingredients for this recipe</h2>
<% if @recipe.ingredients.any? %>
<%  @recipe.ingredients.each do |ingredient| %>

   <p><%= link_to ingredient.name, ingredient_path(ingredient.id) %></p>


<%  end %>
<%  else %>
<p>There are no ingrediernts for this recipe yet</p>

<%  end %>

<h2>Tags for this recipe</h2>
<% if @recipe.tags.any? %>
<%  @recipe.tags.each do |tag| %>

   <p><%=  link_to tag.name, tag_path(tag.id) %></p>


<%  end %>
<%  else %>
<p>There are no Tags for this recipe yet</p>

<%  end %>
<% if @ingredients.any? %>
<%= form_for "ingredient", :url => {:action => "add"} do |f| %>
<%= f.submit "Add Ingredient" %>
<%= f.select :ingredient, @ingredients %>
<%  end %>
<%  end %>

<% if @tags.any? %>
<%= form_for "tag", :url => {:action => "add"} do |f| %>
<%= f.submit "Add Tag" %>
<%= f.select :tag, @tags %>
<%  end %>
<%  end %>

<p><%= link_to "Edit", edit_recipe_path(@recipe) %></p>
<p><%= link_to "Delete", recipe_path(@recipe),
  :data => {:confirm => "You sure?",
  :method => "delete"} %></p>

  <p><%= link_to "Return to recipes", root_path %></p>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= form_for @tag do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/tags/new.html.erb
<h1>Edit Tag</h1>

<%= form_for @tag do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>



<h2>Recipes tagged as <%= @tag.name %></h2>
<% if @tag.recipes.any? %>
<%  @tag.recipes.each do |recipe| %>

   <p><%=  link_to recipe.name, recipe_path(recipe.id) %></p>


<%  end %>
<%  else %>
<p>There are no recipes for this tag yet</p>

<%  end %>


<p><%= link_to "Edit", edit_tag_path(@tag) %></p>
<p><%= link_to "Delete", tag_path(@tag),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to ingredients", root_path %></p>